version: "3"

services:
  server:
    container_name: datagaze-server
    build:
      context: ./server
    stdin_open: true
    tty: true
    working_dir: /src
    ports:
      - "8000:8000"
    volumes:
      - ./server:/src
      - run_vol:/var/run
      - cache_vol:/var/cache
      - tmp_vol:/tmp
    env_file:
      - .env.dev
    command: >
      sh -c "python manage.py makemigrations connectionAPI &&
              python manage.py makemigrations && 
              python manage.py migrate &&
              python manage.py shell < tools/create_superuser.py &&
              python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  client:
    container_name: datagaze-client
    build:
      context: ./client
    volumes:
      - ./client:/usr/app
      - /usr/client/node_modules
    ports:
      - 3000:3000
    env_file:
      - .env.dev
    command: >
      sh -c "npm install &&
             npm start"

  db:
    container_name: datagaze-db
    image: postgres
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    

volumes:
  run_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs
  cache_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs
  tmp_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs
